BEGIN;

-- GENERATED ALWAYS AS IDENTITY was not applied by Supabase migration runner.
-- Add identity sequences to all tables, restarting after existing max IDs.

ALTER TABLE custodians           ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 6);
ALTER TABLE stocks               ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 9);
ALTER TABLE mint_proposals       ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 3);
ALTER TABLE mint_attestations    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 7);
ALTER TABLE stock_transactions   ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 4);
ALTER TABLE stock_attestations   ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 4);
ALTER TABLE wallet_verifications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);
ALTER TABLE redeem_proposals     ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);
ALTER TABLE redeem_attestations  ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 1);

COMMIT;
